tweak fedora install scripts

diff --git a/install-scripts/fedora_dotfiles b/install-scripts/fedora_dotfiles
--- a/install-scripts/fedora_dotfiles
+++ b/install-scripts/fedora_dotfiles
@@ -9,18 +9,18 @@ DOTFILES_REPO="git@github.com:EmilioLombardo/dotfiles.git"
 
 sudo dnf install -y git stow
 
-if [ -d "$DOTFILES_DIR/.git" ]; then
-  echo "Dotfiles repo already exists at:"
-  echo "  $DOTFILES_DIR"
-  echo
-  echo "Pulling latest changes."
-  git -C "$DOTFILES_DIR" pull --ff-only
-elif [ -e "$DOTFILES_DIR" ]; then
-  echo "Error: $DOTFILES_DIR exists but is not a Git repo." >&2
-  exit 1
-else
-  git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
-fi
+# if [ -d "$DOTFILES_DIR/.git" ]; then
+#   echo "Dotfiles repo already exists at:"
+#   echo "  $DOTFILES_DIR"
+#   echo
+#   echo "Pulling latest changes."
+#   git -C "$DOTFILES_DIR" pull --ff-only
+# elif [ -e "$DOTFILES_DIR" ]; then
+#   echo "Error: $DOTFILES_DIR exists but is not a Git repo." >&2
+#   exit 1
+# else
+#   git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
+# fi
 
 if [ ! -f "$DOTFILES_DIR/zshrc-template/.zshrc" ]; then
   echo "Error: missing template:" >&2
